title:              CBC - blog
email:              your-email@example.com
description:        𝗚𝗲𝗺𝗲𝗶𝗻𝘀𝗮𝗺 𝗹ö𝘀𝗲𝗻 𝘄𝗶𝗿 𝗱𝗮𝘀 𝗞𝗼𝗺𝗽𝗹𝗲𝘅𝗲
author:             CBC
baseurl:            "/"
url:                "https://crack-brained.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
